server:
  port: 8082
spring:
  application:
    name: order-service
# security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/glsid-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/glsid-realm
  config:
    import: optional:configserver:http://localhost:8888
