server:
  port: 8082
spring:
  application:
    name: order-service
  cloud:
    discovery:
      enabled: true
    config:
        enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:order-db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/glsid-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/glsid-realm
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/