server:
  port: 8081
spring:
  application:
    name: inventory-service
  # security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/glsid-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/glsid-realm
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}
