logging:
  level:
    org.springframework.security.web: DEBUG
server:
  port: 8081
spring:
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:product-db
  h2:
    console:
      enabled: true
  cloud:
    config:
      discovery:
        enabled: false
    discovery:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
            jwk-set-uri: http://localhost:8080/realms/glsid-realm/protocol/openid-connect/certs
            issuer-uri: http://localhost:8080/realms/glsid-realm
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/